[package]
name = "hdt"
version = "0.1.1"
repository = "https://github.com/konradhoeffner/hdt-rust"
authors = ["Tim Baccaert <tbaccaer@vub.be>"]
license = "MIT"
description = "Library for the Header Dictionary Triples (HDT) RDF compression format."
keywords = ["rdf", "hdt", "header dictionary triples", "compression", "file format"]
categories = ["compression", "filesystem", "parsing", "web-programming"]
edition = "2018"

[dependencies]
crc-any = "2.3"
iref = "1.4"
langtag = "^0.2"
ntriple = "^0.1.1"
