[package]
name = "hdt"
version = "0.0.2"
repository = "https://github.com/konradhoeffner/hdt"
authors = ["Tim Baccaert <tbaccaer@vub.be>", "Konrad Höffner"]
license = "MIT"
description = "Library for the Header Dictionary Triples (HDT) RDF compression format."
keywords = ["rdf", "hdt", "compression", "file-format"]
categories = ["compression", "filesystem", "parsing", "web-programming"]
edition = "2021"

[lib]
doctest = false

[dependencies]
bytesize = "1.1.0"
crc-any = "2.3"
iref = "2.2"
langtag = "^0.3.2"
ntriple = "^0.1.1"
rayon = "1.5.3"
rsdict = "0.0.5"
sophia = { version = "0.7", optional = true }
sucds = "0.5.0"

[features]
default = ["sophia_graph"]
sophia_graph = ["sophia"]

[profile.test]
opt-level = 1

[dev-dependencies]
pretty_assertions = "1.3"
